/**
 * Generated by scripts/optimize-images.ts. Do not edit by hand.
 *
 * Intrinsic dimensions and variant lists for the archival plates, keyed by the
 * logical plate path the content blocks declare. Emitting these into the bundle
 * is what lets every <img> carry a real width/height and a srcset, which is the
 * difference between a page that reserves the right box before the image
 * arrives and one that jumps as it loads.
 */

export interface PlateSource {
  width: number
  height: number
  webp: string[]
  fallback: string | null
}

export const IMAGE_MANIFEST: Record<string, PlateSource> = {
  '/images/osho/osho-air-rajneesh': {
    width: 900,
    height: 626,
    webp: ['/images/osho/osho-air-rajneesh-400.webp', '/images/osho/osho-air-rajneesh-900.webp'],
    fallback: '/images/osho/osho-air-rajneesh-900.jpg',
  },
  '/images/osho/osho-drive-by': {
    width: 400,
    height: 268,
    webp: ['/images/osho/osho-drive-by-400.webp'],
    fallback: '/images/osho/osho-drive-by-400.jpg',
  },
  '/images/osho/osho-festival-1983': {
    width: 400,
    height: 268,
    webp: ['/images/osho/osho-festival-1983-400.webp'],
    fallback: '/images/osho/osho-festival-1983-400.jpg',
  },
  '/images/osho/osho-poona-1977': {
    width: 900,
    height: 532,
    webp: ['/images/osho/osho-poona-1977-400.webp', '/images/osho/osho-poona-1977-900.webp'],
    fallback: '/images/osho/osho-poona-1977-900.jpg',
  },
  '/images/osho/osho-portrait-close': {
    width: 900,
    height: 631,
    webp: ['/images/osho/osho-portrait-close-400.webp', '/images/osho/osho-portrait-close-900.webp'],
    fallback: '/images/osho/osho-portrait-close-900.jpg',
  },
  '/images/osho/osho-portrait-zen': {
    width: 400,
    height: 306,
    webp: ['/images/osho/osho-portrait-zen-400.webp'],
    fallback: '/images/osho/osho-portrait-zen-400.jpg',
  },
  '/images/osho/osho-portrait': {
    width: 900,
    height: 683,
    webp: ['/images/osho/osho-portrait-400.webp', '/images/osho/osho-portrait-900.webp'],
    fallback: '/images/osho/osho-portrait-900.jpg',
  },
}
